apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-app
  labels:
    app: fastfood-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-app
  template:
    metadata:
      name: fastfood-app
      labels:
        app: fastfood-app
    spec:
      containers:
        - name: fastfood-app
          image: fastfood-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
      restartPolicy: Always