apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-app
  labels:
    app: fastfood-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-app
  template:
    metadata:
      name: fastfood-app
      labels:
        app: fastfood-app
    spec:
      containers:
        - name: fastfood-app
          image: fastfood-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      restartPolicy: Always